services:
  app:
    build:
      context: .
    image: data-dreamers-group3
    container_name: data-dreamers-group3
    ports:
      - "3001:3000"
    env_file:
      - .env.local
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
        - action: rebuild
          path: ./package.json
    # ホットリロード
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    command: pnpm dev

