services:
  app:
    build:
      context: .
    image: data-dreamers-group3
    container_name: data-dreamers-group3
    ports:
      - "3001:3000"
    env_file:
      - .env.local
    volumes:
      - node_modules:/app/node_modules
      - ./public:/app/public
      - ./src:/app/src
    # ホットリロード
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
